version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123

  app:
    build: .
    restart: always
    ports:
      - '5001:5001'
    environment:
      DATABASE_URL: postgres://postgres:pass123@db:5432/postgres
    depends_on:
      - db
