version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123

  # Socat sidecar to forward container's :9000 to the host's :9000
  socat:
    image: alpine/socat
    command: >
      tcp-listen:9000,fork,reuseaddr
      tcp:host.docker.internal:9000
    # For Linux hosts, replace host.docker.internal with your actual IP or 172.17.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
    restart: always

  app:
    build: .
    restart: always
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "postgres://postgres:pass123@db:5432/postgres"
      EIKON_APP_KEY: "20af0572a6364fe8abf9a35cdd16bd367057564a"
    depends_on:
      - db
      - socat
